#!/bin/bash

read -p "Press [Enter] key to continue and install programms."

echo "installing epel-release..."
sudo yum install epel-release -y > /dev/null 2>&1

echo "epel-release installed. Pausing for package update..."
sudo yum update -y > /dev/null 2>&1

echo "Installing programs..."
sudo yum install vim net-tools bat wget htop tree neofetch tar zip bash-completion NetworkManager-initscripts-updown -y > /dev/null 2>&1

echo "All specified packages installed successfully."
