apiVersion: v1
kind: Service
metadata:
  name: adapter-azericard-ufx-service
  namespace: test
  labels:
    app: adapter-azericard-ufx
    env: test
spec:
  selector:
    app: adapter-azericard-ufx
    env: test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
  
