apiVersion: apps/v1
kind: Deployment
metadata:
  name: payout-service-t
  namespace: test
  labels:
    app: payout-service
    env: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payout-service
      env: test
  template:
    metadata:
      labels:
        app: payout-service
        env: test
    spec:
      volumes:
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/Asia/Baku
            type: ''
      containers:
        - name: payout-service
          image: hub.goldenpay.az/private/payout-service:v1
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: PROFILE
              value: test
            - name: TZ
              value: Asia/Baku
          resources:
            limits:
              cpu: 512m
              memory: 512Mi
            requests:
              cpu: 64m
              memory: 64Mi
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          imagePullPolicy: IfNotPresent
      schedulerName: default-scheduler
