apiVersion: apps/v1
kind: Deployment
metadata:
  name: payout-service-p
  labels:
    app: payout-service
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payout-service
      env: prod
  template:
    metadata:
      labels:
        app: payout-service
        env: prod
    spec:
      containers:
        - name: payout-service
          image: hub.goldenpay.az/private/payout-service:v1
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          imagePullPolicy: IfNotPresent
      schedulerName: default-scheduler
