apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payout-service-t
    env: test
  name: payout-service-t-t
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payout-service-t
      env: test
  template:
    metadata:
      labels:
        app: payout-service-t
        env: test
      namespace: test
    spec:
      containers:
      - env:
        - name: PROFILE
          value: test
        - name: TZ
          value: Asia/Baku
        image: hub.goldenpay.az/private/payout-service-t-t:v1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 150
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1
        name: payout-service-t
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 512m
            memory: 512Mi
          requests:
            cpu: 64m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: tz-config
      imagePullSecrets:
      - name: golden-hub
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Baku
          type: ""
        name: tz-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: payout-service-t
    env: test
  name: payout-service-t
  namespace: test
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: payout-service-t
    env: test
  type: ClusterIP
